[build-system]
requires = ["uv", "setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pre-commit-starter"
version = "0.1.0"
description = "A starter CLI tool for pre-commit configurations"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Pre-Commit Starter Team"}
]
keywords = ["pre-commit", "git", "hooks", "linting", "configuration", "automation", "starter"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Version Control :: Git",
]
dependencies = [
    "PyYAML==6.0.2",
    "rich==14.0.0",
    "markdown-it-py==3.0.0",
    "mdurl==0.1.2",
    "pygments==2.19.1",
]

[project.optional-dependencies]
dev = [
    "attrs==25.3.0",
    "cfgv==3.4.0",
    "coverage==7.8.0",
    "distlib==0.3.9",
    "filelock==3.18.0",
    "hypothesis==6.131.6",
    "identify==2.6.9",
    "iniconfig==2.1.0",
    "markdown-it-py==3.0.0",
    "mdurl==0.1.2",
    "mypy==1.15.0",
    "mypy-extensions==1.0.0",
    "nodeenv==1.9.1",
    "packaging==24.2",
    "platformdirs==4.3.7",
    "pluggy==1.5.0",
    "pre-commit==4.2.0",
    "pygments==2.19.1",
    "pytest==8.3.5",
    "pytest-cov==6.1.1",
    "PyYAML==6.0.2",
    "rich==14.0.0",
    "ruff==0.11.6",
    "sortedcontainers==2.4.0",
    "typing-extensions==4.13.2",
    "virtualenv==20.30.0",
]

[project.scripts]
pre-commit-starter = "pre_commit_starter.main:main"

[tool.setuptools]

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "B", "I", "N", "UP", "PL", "RUF"]
ignore = ["PLR0912", "PLR0915"]
fixable = ["I", "F", "RUF"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"src/pre_commit_starter/detector/file_scanner.py" = ["PLR0912", "PLR0915"]
"src/pre_commit_starter/generator/yaml_builder.py" = ["PLR0912"]

[tool.black]
line-length = 100
target-version = ["py39"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
)/
'''

[tool.uv]

[tool.pytest.ini_options]
markers = [
    "integration: marks tests as integration tests (deselect with '-m \"not integration\"')",
]
